name: Deploy Node App to Azure VM

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '18'  

    - name: Install dependencies
      run: npm install  

    - name: Deploy to Azure VM using SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem  # Stores SSH key in a file
        chmod 600 key.pem  
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          cd ~/node_app  
          git pull origin main  
          pm2 restart app.js  
        EOF
